### ISSUE TITLE
Laravel 5.3 support?

### ISSUE THREAD

**Issue by bcoughlin** [contentful/contentful-laravel#11]
Is Laravel 5.0 the only version supported?

**Comment by bcoughlin** [comment]
On Laravel 5.3 running this command:
`php artisan vendor:publish --provider='Contentful/Laravel/ContentfulServiceProvider'`

Return this response:
`Nothing to publish for tag [].`

But running `vendor:publish` without `--provider` argument seemed to work.

**Comment by dborsatto** [comment]
Hey @bcoughlin,

thanks for reaching out. I think there's a typo in our doc: the provider argument should use backslashes instead of forward slashes, therefore making it:

`php artisan vendor:publish --provider='Contentful\Laravel\ContentfulServiceProvider'`

Try giving this a shot, optionally using the `--force` parameter and/or running `php artisan config:clear`. Let me know if this helps, in the meanwhile I'll make sure to fix the documentation.

Thanks!
